from keywords_tokenizer import tokenize
from collections import Counter


def main():
    text = """Azathioprine as an oral corticosteroid sparing agent for asthma BACKGROUND: For the majority of chronic asthmatics, symptoms are best controlled by using inhaled steroids. However, for a small group of asthmatics, symptoms can only be controlled by high doses of oral steroids. Continuous use of oral steroid is associated with severe side-effects, but it has been suggested that azathioprine, an immunosuppressive anti-metabolite, often used to reduce the immune response in chronic active hepatitis and severe rheumatoid arthritis, could be useful as an oral steroid sparing agent. There is a need to systematically evaluate the evidence regarding its use to reduce or eliminate oral corticosteroid usage. OBJECTIVES: The objective of this review is to assess the efficacy of adding azathioprine in patients with stable asthma who are dependent on oral corticosteroids with the intention of eventually minimizing or eliminating the use of these steroids. SEARCH STRATEGY: Searches of the Cochrane Airways Group Specialised Register were undertaken with predefined search terms. Searches were current as of August 2010. SELECTION CRITERIA: Only studies with a randomised placebo-controlled design met the inclusion criteria for the review. DATA COLLECTION AND ANALYSIS: Two authors independently assessed studies for suitability for inclusion in the review. Data were extracted and entered into Review Manager. MAIN RESULTS: Two small trials recruiting 23 participants met the inclusion criteria for the review. Participants may have been suffering from comorbid lung disease. No data on oral steroid consumption were reported. No significant differences were observed in the studies for FEV1, FVC, PaO2 and symptoms. One study reported a statistically significant difference in SGaw, but the clinical importance of this is uncertain. Due to concerns over the small sample sizes and methodological shortcomings in terms of inadequate washout in one study, and methods used in outcome assessment for both studies, the findings of the studies are not generalisable to the issue of steroid tapering. An update search conducted in August 2010 did not identify any new studies for consideration in the review. AUTHORS' CONCLUSIONS: Currently there is a clear lack of evidence to support the use of azathioprine in the treatment of chronic asthma as a steroid sparing-agent. Large, long-term studies with pre-defined steroid reducing protocols are required before recommendations for clinical practice can be made."""

    counter_el = Counter(tokenize(text))
    print(counter_el.most_common())


if __name__ == '__main__':
    main()
